package com.example.etymo.screens

import java.util.Locale

data class Script(
    val name: String,
    val emoji: String,
    val locale: Locale,
    val characters: List<ScriptCharacter>
)

data class ScriptCharacter(
    val char: String,
    val romanized: String,
    val pronunciation: String = ""
)

val availableScripts = listOf(
    Script(
        name = "Devnagri",
        emoji = "🕉",
        locale = Locale("hi", "IN"),
        characters = listOf(
            // Vowels
            ScriptCharacter("अ", "a", "uh"),
            ScriptCharacter("आ", "aa", "ah"),
            ScriptCharacter("इ", "i", "ih"),
            ScriptCharacter("ई", "ee", "ee"),
            ScriptCharacter("उ", "u", "oo"),
            ScriptCharacter("ऊ", "oo", "oo"),
            ScriptCharacter("ए", "e", "ay"),
            ScriptCharacter("ऐ", "ai", "eye"),
            ScriptCharacter("ओ", "o", "oh"),
            ScriptCharacter("औ", "au", "ow"),
            ScriptCharacter("अं", "am", "um"),
            ScriptCharacter("अः", "ah", "aha"),
            // Consonants
            ScriptCharacter("क", "ka", "kuh"),
            ScriptCharacter("ख", "kha", "khuh"),
            ScriptCharacter("ग", "ga", "guh"),
            ScriptCharacter("घ", "gha", "ghuh"),
            ScriptCharacter("ङ", "nga", "nguh"),
            ScriptCharacter("च", "cha", "chuh"),
            ScriptCharacter("छ", "chha", "chhuh"),
            ScriptCharacter("ज", "ja", "juh"),
            ScriptCharacter("झ", "jha", "jhuh"),
            ScriptCharacter("ञ", "nya", "nyuh"),
            ScriptCharacter("ट", "ta", "tuh"),
            ScriptCharacter("ठ", "tha", "thuh"),
            ScriptCharacter("ड", "da", "duh"),
            ScriptCharacter("ढ", "dha", "dhuh"),
            ScriptCharacter("ण", "na", "nuh"),
            ScriptCharacter("त", "ta", "tuh"),
            ScriptCharacter("थ", "tha", "thuh"),
            ScriptCharacter("द", "da", "duh"),
            ScriptCharacter("ध", "dha", "dhuh"),
            ScriptCharacter("न", "na", "nuh"),
            ScriptCharacter("प", "pa", "puh"),
            ScriptCharacter("फ", "pha", "phuh"),
            ScriptCharacter("ब", "ba", "buh"),
            ScriptCharacter("भ", "bha", "bhuh"),
            ScriptCharacter("म", "ma", "muh"),
            ScriptCharacter("य", "ya", "yuh"),
            ScriptCharacter("र", "ra", "ruh"),
            ScriptCharacter("ल", "la", "luh"),
            ScriptCharacter("व", "va", "vuh"),
            ScriptCharacter("श", "sha", "shuh"),
            ScriptCharacter("ष", "sha", "shuh"),
            ScriptCharacter("स", "sa", "suh"),
            ScriptCharacter("ह", "ha", "huh"),
            ScriptCharacter("क्ष", "ksha", "kshuh"),
            ScriptCharacter("त्र", "tra", "truh"),
            ScriptCharacter("ज्ञ", "gya", "gyuh"),
        )
    ),
    Script(
        name = "Tamil",
        emoji = "🌿",
        locale = Locale("ta", "IN"),
        characters = listOf(
            // Vowels
            ScriptCharacter("அ", "a"),
            ScriptCharacter("ஆ", "aa"),
            ScriptCharacter("இ", "i"),
            ScriptCharacter("ஈ", "ee"),
            ScriptCharacter("உ", "u"),
            ScriptCharacter("ஊ", "oo"),
            ScriptCharacter("எ", "e"),
            ScriptCharacter("ஏ", "ae"),
            ScriptCharacter("ஐ", "ai"),
            ScriptCharacter("ஒ", "o"),
            ScriptCharacter("ஓ", "oo"),
            ScriptCharacter("ஔ", "au"),
            // Consonants
            ScriptCharacter("க", "ka"),
            ScriptCharacter("ங", "nga"),
            ScriptCharacter("ச", "cha"),
            ScriptCharacter("ஞ", "nya"),
            ScriptCharacter("ட", "ta"),
            ScriptCharacter("ண", "na"),
            ScriptCharacter("த", "tha"),
            ScriptCharacter("ந", "nha"),
            ScriptCharacter("ப", "pa"),
            ScriptCharacter("ம", "ma"),
            ScriptCharacter("ய", "ya"),
            ScriptCharacter("ர", "ra"),
            ScriptCharacter("ல", "la"),
            ScriptCharacter("வ", "va"),
            ScriptCharacter("ழ", "zha"),
            ScriptCharacter("ள", "la"),
            ScriptCharacter("ற", "ra"),
            ScriptCharacter("ன", "na"),
        )
    ),
    Script(
        name = "Kannada",
        emoji = "🏛",
        locale = Locale("kn", "IN"),
        characters = listOf(
            // Vowels
            ScriptCharacter("ಅ", "a"),
            ScriptCharacter("ಆ", "aa"),
            ScriptCharacter("ಇ", "i"),
            ScriptCharacter("ಈ", "ee"),
            ScriptCharacter("ಉ", "u"),
            ScriptCharacter("ಊ", "oo"),
            ScriptCharacter("ಎ", "e"),
            ScriptCharacter("ಏ", "ae"),
            ScriptCharacter("ಐ", "ai"),
            ScriptCharacter("ಒ", "o"),
            ScriptCharacter("ಓ", "oo"),
            ScriptCharacter("ಔ", "au"),
            // Consonants
            ScriptCharacter("ಕ", "ka"),
            ScriptCharacter("ಖ", "kha"),
            ScriptCharacter("ಗ", "ga"),
            ScriptCharacter("ಘ", "gha"),
            ScriptCharacter("ಙ", "nga"),
            ScriptCharacter("ಚ", "cha"),
            ScriptCharacter("ಛ", "chha"),
            ScriptCharacter("ಜ", "ja"),
            ScriptCharacter("ಝ", "jha"),
            ScriptCharacter("ಞ", "nya"),
            ScriptCharacter("ಟ", "ta"),
            ScriptCharacter("ಡ", "da"),
            ScriptCharacter("ತ", "tha"),
            ScriptCharacter("ದ", "dha"),
            ScriptCharacter("ನ", "na"),
            ScriptCharacter("ಪ", "pa"),
            ScriptCharacter("ಬ", "ba"),
            ScriptCharacter("ಮ", "ma"),
        )
    ),
    Script(
        name = "Bengali",
        emoji = "🪻",
        locale = Locale("bn", "IN"),
        characters = listOf(
            // Vowels
            ScriptCharacter("অ", "a"),
            ScriptCharacter("আ", "aa"),
            ScriptCharacter("ই", "i"),
            ScriptCharacter("ঈ", "ee"),
            ScriptCharacter("উ", "u"),
            ScriptCharacter("ঊ", "oo"),
            ScriptCharacter("এ", "e"),
            ScriptCharacter("ঐ", "ai"),
            ScriptCharacter("ও", "o"),
            ScriptCharacter("ঔ", "au"),
            // Consonants
            ScriptCharacter("ক", "ka"),
            ScriptCharacter("খ", "kha"),
            ScriptCharacter("গ", "ga"),
            ScriptCharacter("ঘ", "gha"),
            ScriptCharacter("ঙ", "nga"),
            ScriptCharacter("চ", "cha"),
            ScriptCharacter("ছ", "chha"),
            ScriptCharacter("জ", "ja"),
            ScriptCharacter("ঝ", "jha"),
            ScriptCharacter("ঞ", "nya"),
            ScriptCharacter("ট", "ta"),
            ScriptCharacter("ড", "da"),
            ScriptCharacter("ত", "tha"),
            ScriptCharacter("দ", "dha"),
            ScriptCharacter("ন", "na"),
            ScriptCharacter("প", "pa"),
            ScriptCharacter("ব", "ba"),
            ScriptCharacter("ম", "ma"),
            ScriptCharacter("য", "ja"),
            ScriptCharacter("র", "ra"),
            ScriptCharacter("ল", "la"),
        )
    ),
    Script(
        name = "Japanese",
        emoji = "🗾",
        locale = Locale("ja", "JP"),
        characters = listOf(
            // Hiragana — basic vowels and consonant rows
            ScriptCharacter("あ", "a"),
            ScriptCharacter("い", "i"),
            ScriptCharacter("う", "u"),
            ScriptCharacter("え", "e"),
            ScriptCharacter("お", "o"),
            ScriptCharacter("か", "ka"),
            ScriptCharacter("き", "ki"),
            ScriptCharacter("く", "ku"),
            ScriptCharacter("け", "ke"),
            ScriptCharacter("こ", "ko"),
            ScriptCharacter("さ", "sa"),
            ScriptCharacter("し", "shi"),
            ScriptCharacter("す", "su"),
            ScriptCharacter("せ", "se"),
            ScriptCharacter("そ", "so"),
            ScriptCharacter("た", "ta"),
            ScriptCharacter("ち", "chi"),
            ScriptCharacter("つ", "tsu"),
            ScriptCharacter("て", "te"),
            ScriptCharacter("と", "to"),
            ScriptCharacter("な", "na"),
            ScriptCharacter("に", "ni"),
            ScriptCharacter("ぬ", "nu"),
            ScriptCharacter("ね", "ne"),
            ScriptCharacter("の", "no"),
            ScriptCharacter("は", "ha"),
            ScriptCharacter("ひ", "hi"),
            ScriptCharacter("ふ", "fu"),
            ScriptCharacter("へ", "he"),
            ScriptCharacter("ほ", "ho"),
            ScriptCharacter("ま", "ma"),
            ScriptCharacter("み", "mi"),
            ScriptCharacter("む", "mu"),
            ScriptCharacter("め", "me"),
            ScriptCharacter("も", "mo"),
            ScriptCharacter("や", "ya"),
            ScriptCharacter("ゆ", "yu"),
            ScriptCharacter("よ", "yo"),
            ScriptCharacter("ら", "ra"),
            ScriptCharacter("り", "ri"),
            ScriptCharacter("る", "ru"),
            ScriptCharacter("れ", "re"),
            ScriptCharacter("ろ", "ro"),
            ScriptCharacter("わ", "wa"),
            ScriptCharacter("を", "wo"),
            ScriptCharacter("ん", "n"),
        )
    ),
)
