package com.example.etymo.screens

data class Script(
    val name: String,
    val emoji: String,
    val characters: List<ScriptCharacter>
)

data class ScriptCharacter(
    val char: String,
    val romanized: String,
    val pronunciation: String = ""
)

val availableScripts = listOf(
    Script(
        name = "Devanagari",
        emoji = "🕉",
        characters = listOf(
            // Vowels
            ScriptCharacter("अ", "a", "uh"),
            ScriptCharacter("आ", "aa", "ah"),
            ScriptCharacter("इ", "i", "ih"),
            ScriptCharacter("ई", "ee", "ee"),
            ScriptCharacter("उ", "u", "oo"),
            ScriptCharacter("ऊ", "oo", "oo"),
            ScriptCharacter("ए", "e", "ay"),
            ScriptCharacter("ऐ", "ai", "eye"),
            ScriptCharacter("ओ", "o", "oh"),
            ScriptCharacter("औ", "au", "ow"),
            // Consonants
            ScriptCharacter("क", "ka", "kuh"),
            ScriptCharacter("ख", "kha", "khuh"),
            ScriptCharacter("ग", "ga", "guh"),
            ScriptCharacter("घ", "gha", "ghuh"),
            ScriptCharacter("च", "cha", "chuh"),
            ScriptCharacter("छ", "chha", "chhuh"),
            ScriptCharacter("ज", "ja", "juh"),
            ScriptCharacter("झ", "jha", "jhuh"),
            ScriptCharacter("ट", "ta", "tuh"),
            ScriptCharacter("ठ", "tha", "thuh"),
            ScriptCharacter("ड", "da", "duh"),
            ScriptCharacter("ढ", "dha", "dhuh"),
            ScriptCharacter("ण", "na", "nuh"),
            ScriptCharacter("त", "ta", "tuh"),
            ScriptCharacter("थ", "tha", "thuh"),
            ScriptCharacter("द", "da", "duh"),
            ScriptCharacter("ध", "dha", "dhuh"),
            ScriptCharacter("न", "na", "nuh"),
            ScriptCharacter("प", "pa", "puh"),
            ScriptCharacter("फ", "pha", "phuh"),
            ScriptCharacter("ब", "ba", "buh"),
            ScriptCharacter("भ", "bha", "bhuh"),
            ScriptCharacter("म", "ma", "muh"),
            ScriptCharacter("य", "ya", "yuh"),
            ScriptCharacter("र", "ra", "ruh"),
            ScriptCharacter("ल", "la", "luh"),
            ScriptCharacter("व", "va", "vuh"),
            ScriptCharacter("श", "sha", "shuh"),
            ScriptCharacter("ष", "sha", "shuh"),
            ScriptCharacter("स", "sa", "suh"),
            ScriptCharacter("ह", "ha", "huh"),
        )
    ),
    Script(
        name = "Tamil",
        emoji = "🌿",
        characters = listOf(
            ScriptCharacter("அ", "a"),
            ScriptCharacter("ஆ", "aa"),
            ScriptCharacter("இ", "i"),
            ScriptCharacter("ஈ", "ee"),
            ScriptCharacter("உ", "u"),
            ScriptCharacter("ஊ", "oo"),
            ScriptCharacter("எ", "e"),
            ScriptCharacter("ஏ", "ae"),
            ScriptCharacter("ஐ", "ai"),
            ScriptCharacter("ஒ", "o"),
            ScriptCharacter("ஓ", "oo"),
            ScriptCharacter("ஔ", "au"),
            ScriptCharacter("க", "ka"),
            ScriptCharacter("ங", "nga"),
            ScriptCharacter("ச", "cha"),
            ScriptCharacter("ஞ", "nya"),
            ScriptCharacter("ட", "ta"),
            ScriptCharacter("ண", "na"),
            ScriptCharacter("த", "tha"),
            ScriptCharacter("ந", "nha"),
            ScriptCharacter("ப", "pa"),
            ScriptCharacter("ம", "ma"),
            ScriptCharacter("ய", "ya"),
            ScriptCharacter("ர", "ra"),
            ScriptCharacter("ல", "la"),
            ScriptCharacter("வ", "va"),
        )
    ),
    Script(
        name = "Telugu",
        emoji = "🪷",
        characters = listOf(
            ScriptCharacter("అ", "a"),
            ScriptCharacter("ఆ", "aa"),
            ScriptCharacter("ఇ", "i"),
            ScriptCharacter("ఈ", "ee"),
            ScriptCharacter("ఉ", "u"),
            ScriptCharacter("ఊ", "oo"),
            ScriptCharacter("ఎ", "e"),
            ScriptCharacter("ఏ", "ae"),
            ScriptCharacter("ఐ", "ai"),
            ScriptCharacter("ఒ", "o"),
            ScriptCharacter("ఓ", "oo"),
            ScriptCharacter("ఔ", "au"),
            ScriptCharacter("క", "ka"),
            ScriptCharacter("ఖ", "kha"),
            ScriptCharacter("గ", "ga"),
            ScriptCharacter("ఘ", "gha"),
            ScriptCharacter("చ", "cha"),
            ScriptCharacter("జ", "ja"),
            ScriptCharacter("ట", "ta"),
            ScriptCharacter("డ", "da"),
            ScriptCharacter("త", "tha"),
            ScriptCharacter("ద", "dha"),
            ScriptCharacter("న", "na"),
            ScriptCharacter("ప", "pa"),
            ScriptCharacter("బ", "ba"),
            ScriptCharacter("మ", "ma"),
        )
    ),
    Script(
        name = "Kannada",
        emoji = "🏛",
        characters = listOf(
            ScriptCharacter("ಅ", "a"),
            ScriptCharacter("ಆ", "aa"),
            ScriptCharacter("ಇ", "i"),
            ScriptCharacter("ಈ", "ee"),
            ScriptCharacter("ಉ", "u"),
            ScriptCharacter("ಊ", "oo"),
            ScriptCharacter("ಎ", "e"),
            ScriptCharacter("ಏ", "ae"),
            ScriptCharacter("ಐ", "ai"),
            ScriptCharacter("ಒ", "o"),
            ScriptCharacter("ಓ", "oo"),
            ScriptCharacter("ಔ", "au"),
            ScriptCharacter("ಕ", "ka"),
            ScriptCharacter("ಖ", "kha"),
            ScriptCharacter("ಗ", "ga"),
            ScriptCharacter("ಘ", "gha"),
            ScriptCharacter("ಚ", "cha"),
            ScriptCharacter("ಜ", "ja"),
            ScriptCharacter("ಟ", "ta"),
            ScriptCharacter("ಡ", "da"),
            ScriptCharacter("ತ", "tha"),
            ScriptCharacter("ದ", "dha"),
            ScriptCharacter("ನ", "na"),
            ScriptCharacter("ಪ", "pa"),
            ScriptCharacter("ಬ", "ba"),
            ScriptCharacter("ಮ", "ma"),
        )
    ),
    Script(
        name = "Bengali",
        emoji = "🪻",
        characters = listOf(
            ScriptCharacter("অ", "a"),
            ScriptCharacter("আ", "aa"),
            ScriptCharacter("ই", "i"),
            ScriptCharacter("ঈ", "ee"),
            ScriptCharacter("উ", "u"),
            ScriptCharacter("ঊ", "oo"),
            ScriptCharacter("এ", "e"),
            ScriptCharacter("ঐ", "ai"),
            ScriptCharacter("ও", "o"),
            ScriptCharacter("ঔ", "au"),
            ScriptCharacter("ক", "ka"),
            ScriptCharacter("খ", "kha"),
            ScriptCharacter("গ", "ga"),
            ScriptCharacter("ঘ", "gha"),
            ScriptCharacter("চ", "cha"),
            ScriptCharacter("ছ", "chha"),
            ScriptCharacter("জ", "ja"),
            ScriptCharacter("ঝ", "jha"),
            ScriptCharacter("ট", "ta"),
            ScriptCharacter("ড", "da"),
            ScriptCharacter("ত", "tha"),
            ScriptCharacter("দ", "dha"),
            ScriptCharacter("ন", "na"),
            ScriptCharacter("প", "pa"),
            ScriptCharacter("ব", "ba"),
            ScriptCharacter("ম", "ma"),
        )
    ),
    Script(
        name = "Greek",
        emoji = "🏛️",
        characters = listOf(
            ScriptCharacter("Α", "Alpha"),
            ScriptCharacter("Β", "Beta"),
            ScriptCharacter("Γ", "Gamma"),
            ScriptCharacter("Δ", "Delta"),
            ScriptCharacter("Ε", "Epsilon"),
            ScriptCharacter("Ζ", "Zeta"),
            ScriptCharacter("Η", "Eta"),
            ScriptCharacter("Θ", "Theta"),
            ScriptCharacter("Ι", "Iota"),
            ScriptCharacter("Κ", "Kappa"),
            ScriptCharacter("Λ", "Lambda"),
            ScriptCharacter("Μ", "Mu"),
            ScriptCharacter("Ν", "Nu"),
            ScriptCharacter("Ξ", "Xi"),
            ScriptCharacter("Ο", "Omicron"),
            ScriptCharacter("Π", "Pi"),
            ScriptCharacter("Ρ", "Rho"),
            ScriptCharacter("Σ", "Sigma"),
            ScriptCharacter("Τ", "Tau"),
            ScriptCharacter("Υ", "Upsilon"),
            ScriptCharacter("Φ", "Phi"),
            ScriptCharacter("Χ", "Chi"),
            ScriptCharacter("Ψ", "Psi"),
            ScriptCharacter("Ω", "Omega"),
        )
    ),
)
